
rooms = {
    1: {"name": "Cave",
        "description": "dark spooky cave"},
    2: {"name": "Church",
        "description": "grand cathedral"},
    3: {"name": "Outside Cave Entrance",
        "description": "North of you, the cave mount beckons."},
    4: {"name": "Foyer",
        "description": "Dim light filters in from the south. Dusty passages run north and east."},
    5: {"name": "Grand Overlook",
        "description": "A steep cliff appears before you, falling into the darkness. Ahead to the north, a light flickers in the distance, but there is no way across the chasm."},
    6: {"name": "Narrow Passage",
        "description": "The narrow passage bends here from west to north. The smell of gold permeates the air."},
    7: {"name": "Treasure Chamber",
        "description": "You've found the long-lost treasure chamber! Sadly, it has already been completely emptied by earlier adventurers. The only exit is to the south."},
    8: {"name": "Maids Chamber",
        "description": "Dark room full of old antiquities"},
    9: {"name": "King's Dining Room",
        "description": "Large room with massive dinner table "},
    10: {"name": "Courtyard",
        "description": "Outdoor room with a large fountain and benches "},
    11: {"name": "Kitchen",
        "description": "Massive kitchen filled with pots, pans and various cookingware "},
    12: {"name": "Guest Room",
        "description": "Large room with a bed and sleeping quarters for any guests "},
    13: {"name": "Grand Room",
        "description": "Largest room in the Castle with the kings and queens throne inside "},
    14: {"name": "Safe Room",
        "description": "Small room filled with weapons to protect the Queen and King "},
    15: {"name": "Guards Chamber",
        "description": "you've entered the guards chamber, it is filled with beds for the King's guard and swords "},
    16: {"name": "Buttery",
        "description": "you've entered the buttery, it has a distinct smell of butter and other assorted foods "},
    17: {"name": "Library",
        "description": "the dimly lit chamber filled with lanterns and books, a recipe for disaster! "},
    18: {"name": "Icehouse",
        "description": "you've entered the darkest room in the castle, filled with ice and extremely insulated to keep everything inside ;) "},
    19: {"name": "The Dungeon",
        "description": "this is the most dangerous room in the house, most will not return once they enter... "},
    20: {"name": "The Gatehouse",
        "description": "you have entered the gatehouse, over looking the border walls of the castle "},
    21: {"name": "Place of Arms",
        "description": "You have entered the most powerful room in the Castle, you can find weapons and armor in here! "},
    22: {"name": "The Gallery",
        "description": "the gallery is the most historical room in the castle, all prior kings and queens are remembered here! "},
    23: {"name": "North Tower Room",
        "description": "this room over looks the edges of the Castle walls, great for protecting the Castle "},
    24: {"name": "Stable House",
        "description": "you've entered the stable house, filled with beautiful horses and their not so beautiful stench!"},
    25: {"name": "Barbican",
        "description": "beware trespassers the sign says, this room is filled with traps! Tread carefully! "},
    
}