# Generated by Django 3.0.3 on 2020-02-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200204_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='x_coord',
            new_name='x_cord',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='y_coord',
            new_name='y_cord',
        ),
    ]
