# Generated by Django 3.0.3 on 2020-02-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200205_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='x_cord',
            new_name='x_coord',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='y_cord',
            new_name='y_coord',
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
