# Generated by Django 3.0.3 on 2020-02-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_room_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='room',
            name='x',
        ),
    ]
