# Generated by Django 3.0.3 on 2020-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200206_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='x_coord',
            new_name='x_cord',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='y_coord',
            new_name='y_cord',
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
