# Generated by Django 3.0.3 on 2020-02-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20200206_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='x_cord',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='y_cord',
            new_name='y',
        ),
    ]
