# Generated by Django 3.0.3 on 2020-02-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_room_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='x',
        ),
    ]
